CREATE TABLE language
(
    language_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        CHAR(20)                  NOT NULL,
    last_update TIMESTAMPTZ DEFAULT now() NOT NULL
);
