CREATE TABLE actor
(
    actor_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  TEXT                      NOT NULL,
    last_name   TEXT                      NOT NULL,
    last_update TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE INDEX ON actor (last_name);
