CREATE TABLE staff
(
    staff_id    SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  TEXT                                                            NOT NULL,
    last_name   TEXT                                                            NOT NULL,
    address_id  INTEGER REFERENCES address ON UPDATE CASCADE ON DELETE RESTRICT NOT NULL,
    email       TEXT,
    store_id    SMALLINT REFERENCES store                                       NOT NULL,
    active      BOOLEAN     DEFAULT true                                        NOT NULL,
    username    TEXT                                                            NOT NULL,
    password    TEXT,
    last_update TIMESTAMPTZ DEFAULT now()                                       NOT NULL,
    picture     BYTEA
);
