CREATE TABLE rental
(
    rental_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_date  TIMESTAMPTZ                                                       NOT NULL, -- TODO this is not date!!!
    inventory_id INTEGER REFERENCES inventory ON UPDATE CASCADE ON DELETE RESTRICT NOT NULL,
    customer_id  INTEGER REFERENCES customer ON UPDATE CASCADE ON DELETE RESTRICT  NOT NULL,
    return_date  TIMESTAMPTZ,                                                                -- TODO this is not date!!!
    staff_id     SMALLINT REFERENCES staff ON UPDATE CASCADE ON DELETE RESTRICT    NOT NULL,
    last_update  TIMESTAMPTZ DEFAULT now()                                         NOT NULL,
    CONSTRAINT unq_rental_rental_date_inventory_id_customer_id_idx UNIQUE (rental_date, inventory_id, customer_id)
);

CREATE TRIGGER last_updated
    BEFORE UPDATE
    ON rental
    FOR EACH ROW
EXECUTE PROCEDURE last_updated();
